### ISSUE TITLE
Returning `PlanewaveWavefunction` in other functions

### ISSUE THREAD

**Issue by xamberl** [brainandforce/Electrum.jl#160]
I'm having issues returning a  `PlanewaveWavefunction` object as part of a tuple in another function. The particular error message I get is this:

```
ERROR: MethodError: no method matching reshape(::PlanewaveWavefunction{3, ComplexF32}, ::Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}, UnitRange{Int64}, UnitRange{Int64}, UnitRange{Int64}})
Closest candidates are:
  reshape(::AbstractArray{T, N}, ::Val{N}) where {T, N} at reshapedarray.jl:140
  reshape(::AbstractArray, ::Val{N}) where N at reshapedarray.jl:141
  reshape(::AbstractArray, ::Int64...) at reshapedarray.jl:117
```

**Comment by brainandforce** [comment]
I assume this is a function you've written that's external to Electrum - can you provide the rest of that function?

**Comment by brainandforce** [comment]
I discussed this in person, but leaving it here for reference: the bug is not with `PlanewaveWavefunction`, it's in how Julia handles the `show(::IO, [::MIME"text/plain"], ::PlanewaveWavefunction)` method. The return value is correct, but when it attempts to display a `PlanewaveWavefunction` tuple member it fails.
